// Code generated by vected DO NOT EDIT.
package test

import (
	"context"
	"github.com/gernest/vected/prop"
	"github.com/gernest/vected/state"
	"github.com/gernest/vected/vdom"
)

var H = vdom.New
var HA = vdom.Attr
var HAT = vdom.Attrs

// Render implements vected.Renderer interface.
func (t Hello) Render(ctx context.Context, props prop.Props, state state.State) *vdom.Node {
	return H(3, "", "div", HAT(
		HA("", "classname", props["classNames"]),
		HA("", "key", "value")),
		H(3, "", "ul", nil,
			H(3, "", "li", nil,
				H(1, "", "1", nil)),
			H(3, "", "li", nil,
				H(1, "", "2", nil)),
			H(3, "", "li", nil,
				H(1, "", "3", nil)),
			H(3, "", "li", nil,
				H(1, "", "4", nil)),
			H(3, "", "li", nil,
				H(1, "", "5", nil))),
		H(3, "", "ol", nil,
			H(3, "", "li", nil,
				H(1, "", "1", nil)),
			H(3, "", "li", nil,
				H(1, "", "2", nil)),
			H(3, "", "li", nil,
				H(1, "", "3", nil)),
			H(3, "", "li", nil,
				H(1, "", "4", nil)),
			H(3, "", "li", nil,
				H(1, "", "5", nil))))
}
