// Code generated by vected DO NOT EDIT.
package test

import (
	"context"
	"github.com/gernest/vected/props"
	"github.com/gernest/vected/state"
	"github.com/gernest/vected/vdom"
)

// N is an alias for creating a new node
var h = vdom.New
var ha = vdom.Attr
var hat = vdom.Attrs

// Render implements vected.Renderer interface.
func (t Hello) Render(ctx context.Context, props props.Props, state state.State) *vdom.Node {
	return h(3, "", "div", hat(
		ha("", "classname", props["classNames"]),
		ha("", "key", "value")),
		h(3, "", "ul", nil,
			h(3, "", "li", nil,
				h(1, "", "1", nil)),
			h(3, "", "li", nil,
				h(1, "", "2", nil)),
			h(3, "", "li", nil,
				h(1, "", "3", nil)),
			h(3, "", "li", nil,
				h(1, "", "4", nil)),
			h(3, "", "li", nil,
				h(1, "", "5", nil))),
		h(3, "", "ol", nil,
			h(3, "", "li", nil,
				h(1, "", "1", nil)),
			h(3, "", "li", nil,
				h(1, "", "2", nil)),
			h(3, "", "li", nil,
				h(1, "", "3", nil)),
			h(3, "", "li", nil,
				h(1, "", "4", nil)),
			h(3, "", "li", nil,
				h(1, "", "5", nil))))
}
