// Code generated by vected DO NOT EDIT.
package sample

import (
	"github.com/gernest/vected/lib/vdom"
	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

// Render implements vected.Renderer interface.
func (Component) Render() *vdom.Node {
	return &vdom.Node{Children: []*vdom.Node{&vdom.Node{Type: html.ElementNode, DataAtom: atom.Html, Data: "html", Children: []*vdom.Node{&vdom.Node{Type: html.ElementNode, DataAtom: atom.Head, Data: "head"}, &vdom.Node{Type: html.ElementNode, DataAtom: atom.Body, Data: "body", Children: []*vdom.Node{&vdom.Node{Type: html.ElementNode, DataAtom: atom.Div, Data: "div", Children: []*vdom.Node{&vdom.Node{Type: html.TextNode, Data: " hello, world"}}}}}}}}}
}
