package iconfont

import (
	"sort"

	"github.com/gernest/gs"
	"github.com/gernest/vected/web/style/core/themes"
	"github.com/gernest/vected/web/style/mixins"
)

func FontFace() gs.CSSRule {
	u := themes.Default.IconURL
	s := "url('" + u + ".woff')format('woff')," +
		"url('" + u + ".ttf')format('truetype')," +
		"url('" + u + ".iconfont')format('svg')"
	return gs.FontFace(
		gs.P("font-family", `'anticon'`),
		gs.P("src", s),
	)
}

func Font() gs.CSSRule {
	return gs.S("."+themes.Default.IconFontPrefix,
		mixins.IconFontMixin(),
	)
}

func iconByName(name string) gs.CSSRule {
	return gs.S("."+themes.Default.IconFontPrefix+"-"+name,
		gs.S("&:before",
			gs.P("content", icons[name]),
		),
	)
}

func spin() gs.CSSRule {
	return gs.S("."+themes.Default.IconFontPrefix+"-spin:before",
		gs.P("display", "inline-block;"),
		gs.P("animation", "loadingCircle 1s infinite linear"),
	)
}

// FontStyles returns styles for all antd icons.
func FontStyles() gs.CSSRule {
	var list gs.RuleList
	var keys []string
	for k := range icons {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		list = append(list, iconByName(k))
	}
	list = append(list, spin())
	return list
}

var icons = map[string]string{
	"step-forward":         `"\e600"`,
	"step-backward":        `"\e601"`,
	"forward":              `"\e602"`,
	"backward":             `"\e603"`,
	"caret-right":          `"\e604"`,
	"caret-left":           `"\e605"`,
	"caret-down":           `"\e606"`,
	"caret-up":             `"\e607"`,
	"right-circle":         `"\e608"`,
	"circle-right":         `"\e608"`, // antd@1.x compatibility alias: right-circle
	"caret-circle-right":   `"\e608"`, // antd@1.x compatibility alias: right-circle
	"left-circle":          `"\e609"`,
	"circle-left":          `"\e609"`, // antd@1.x compatibility alias: left-circle
	"caret-circle-left":    `"\e609"`, // antd@1.x compatibility alias: left-circle
	"up-circle":            `"\e60a"`,
	"circle-up":            `"\e60a"`, // antd@1.x compatibility alias: up-circle
	"caret-circle-up":      `"\e60a"`, // antd@1.x compatibility alias: up-circle
	"down-circle":          `"\e60b"`,
	"circle-down":          `"\e60b"`, // antd@1.x compatibility alias: down-circle
	"caret-circle-down":    `"\e60b"`, // antd@1.x compatibility alias: down-circle
	"right-circle-o":       `"\e60c"`,
	"circle-o-right":       `"\e60c"`, // antd@1.x compatibility alias: right-circle-o
	"caret-circle-o-right": `"\e60c"`, // antd@1.x compatibility alias: right-circle-o
	"left-circle-o":        `"\e60d"`,
	"circle-o-left":        `"\e60d"`, // antd@1.x compatibility alias: left-circle-o
	"caret-circle-o-left":  `"\e60d"`, // antd@1.x compatibility alias: left-circle-o
	"up-circle-o":          `"\e60e"`,
	"circle-o-up":          `"\e60e"`, // antd@1.x compatibility alias: up-circle-o
	"caret-circle-o-up":    `"\e60e"`, // antd@1.x compatibility alias: up-circle-o
	"down-circle-o":        `"\e60f"`,
	"circle-o-down":        `"\e60f"`, // antd@1.x compatibility alias: down-circle-o
	"caret-circle-o-down":  `"\e60f"`, // antd@1.x compatibility alias: down-circle-o
	"verticle-left":        `"\e610"`,
	"verticle-right":       `"\e611"`,
	"rollback":             `"\e612"`,
	"retweet":              `"\e613"`,
	"shrink":               `"\e614"`,
	"arrows-alt":           `"\e615"`,
	"arrow-salt":           `"\e615"`, // antd@1.x compatibility alias: arrows-alt
	"reload":               `"\e616"`,
	"double-right":         `"\e617"`,
	"double-left":          `"\e618"`,
	"arrow-down":           `"\e619"`,
	"arrow-up":             `"\e61a"`,
	"arrow-right":          `"\e61b"`,
	"arrow-left":           `"\e61c"`,
	"down":                 `"\e61d"`,
	"up":                   `"\e61e"`,
	"right":                `"\e61f"`,
	"left":                 `"\e620"`,
	"minus-square-o":       `"\e621"`,
	"minus-circle":         `"\e622"`,
	"minus-circle-o":       `"\e623"`,
	"minus":                `"\e624"`,
	"plus-circle-o":        `"\e625"`,
	"plus-circle":          `"\e626"`,
	"plus":                 `"\e627"`,
	"info-circle":          `"\e628"`,
	"info-circle-o":        `"\e629"`,
	"info":                 `"\e62a"`,
	"exclamation":          `"\e62b"`,
	"exclamation-circle":   `"\e62c"`,
	"exclamation-circle-o": `"\e62d"`,
	"close-circle":         `"\e62e"`,
	"cross-circle":         `"\e62e"`, // antd@1.x compatibility alias: close-circle
	"close-circle-o":       `"\e62f"`,
	"cross-circle-o":       `"\e62f"`, // antd@1.x compatibility alias: close-circle-o
	"check-circle":         `"\e630"`,
	"check-circle-o":       `"\e631"`,
	"check":                `"\e632"`,
	"close":                `"\e633"`,
	"cross":                `"\e633"`, // antd@1.x compatibility alias: close
	"customer-service":     `"\e634"`,
	"customerservice":      `"\e634"`, // antd@1.x compatibility alias: customer-service
	"credit-card":          `"\e635"`,
	"code-o":               `"\e636"`,
	"book":                 `"\e637"`,
	"bars":                 `"\e639"`,
	"question":             `"\e63a"`,
	"question-circle":      `"\e63b"`,
	"question-circle-o":    `"\e63c"`,
	"pause":                `"\e63d"`,
	"pause-circle":         `"\e63e"`,
	"pause-circle-o":       `"\e63f"`,
	"clock-circle":         `"\e640"`,
	"clock-circle-o":       `"\e641"`,
	"swap":                 `"\e642"`,
	"swap-left":            `"\e643"`,
	"swap-right":           `"\e644"`,
	"plus-square-o":        `"\e645"`,
	"frown":                `"\e646"`,
	"frown-circle":         `"\e646"`, // antd@1.x compatibility alias: frown
	"ellipsis":             `"\e647"`,
	"copy":                 `"\e648"`,
	"menu-fold":            `"\e9ac"`,
	"mail":                 `"\e659"`,
	"logout":               `"\e65a"`,
	"link":                 `"\e65b"`,
	"area-chart":           `"\e65c"`,
	"line-chart":           `"\e65d"`,
	"home":                 `"\e65e"`,
	"laptop":               `"\e65f"`,
	"star":                 `"\e660"`,
	"star-o":               `"\e661"`,
	"folder":               `"\e662"`,
	"filter":               `"\e663"`,
	"file":                 `"\e664"`,
	"exception":            `"\e665"`,
	"meh":                  `"\e666"`,
	"meh-circle":           `"\e666"`, // antd@1.x compatibility alias: meh
	"meh-o":                `"\e667"`,
	"shopping-cart":        `"\e668"`,
	"save":                 `"\e669"`,
	"user":                 `"\e66a"`,
	"video-camera":         `"\e66b"`,
	"to-top":               `"\e66c"`,
	"team":                 `"\e66d"`,
	"tablet":               `"\e66e"`,
	"solution":             `"\e66f"`,
	"search":               `"\e670"`,
	"share-alt":            `"\e671"`,
	"setting":              `"\e672"`,
	"poweroff":             `"\e6d5"`,
	"picture":              `"\e674"`,
	"phone":                `"\e675"`,
	"paper-clip":           `"\e676"`,
	"notification":         `"\e677"`,
	"mobile":               `"\e678"`,
	"menu-unfold":          `"\e9ad"`,
	"inbox":                `"\e67a"`,
	"lock":                 `"\e67b"`,
	"qrcode":               `"\e67c"`,
	"play-circle":          `"\e6d0"`,
	"play-circle-o":        `"\e6d1"`,
	"tag":                  `"\e6d2"`,
	"tag-o":                `"\e6d3"`,
	"tags":                 `"\e67d"`,
	"tags-o":               `"\e67e"`,
	"cloud-o":              `"\e67f"`,
	"cloud":                `"\e680"`,
	"cloud-upload":         `"\e681"`,
	"cloud-download":       `"\e682"`,
	"cloud-download-o":     `"\e683"`,
	"cloud-upload-o":       `"\e684"`,
	"environment":          `"\e685"`,
	"environment-o":        `"\e686"`,
	"eye":                  `"\e687"`,
	"eye-o":                `"\e688"`,
	"camera":               `"\e689"`,
	"camera-o":             `"\e68a"`,
	"windows":              `"\e68b"`,
	"apple":                `"\e68c"`,
	"apple-o":              `"\e6d4"`,
	"android":              `"\e938"`,
	"android-o":            `"\e68d"`,
	"aliwangwang":          `"\e68e"`,
	"aliwangwang-o":        `"\e68f"`,
	"export":               `"\e691"`,
	"edit":                 `"\e692"`,
	"circle-down-o":        `"\e693"`,
	"circle-down-":         `"\e694"`,
	"appstore-o":           `"\e695"`,
	"appstore":             `"\e696"`,
	"scan":                 `"\e697"`,
	"file-text":            `"\e698"`,
	"folder-open":          `"\e699"`,
	"hdd":                  `"\e69a"`,
	"ie":                   `"\e69b"`,
	"file-jpg":             `"\e69c"`,
	"like":                 `"\e64c"`,
	"like-o":               `"\e69d"`,
	"dislike":              `"\e64b"`,
	"dislike-o":            `"\e69e"`,
	"delete":               `"\e69f"`,
	"enter":                `"\e6a0"`,
	"pushpin-o":            `"\e6a1"`,
	"pushpin":              `"\e6a2"`,
	"heart":                `"\e6a3"`,
	"heart-o":              `"\e6a4"`,
	"pay-circle":           `"\e6a5"`,
	"pay-circle-o":         `"\e6a6"`,
	"smile":                `"\e6a7"`,
	"smile-circle":         `"\e6a7"`, // antd@1.x compatibility alias: smile
	"smile-o":              `"\e6a8"`,
	"frown-o":              `"\e6a9"`,
	"calculator":           `"\e6aa"`,
	"message":              `"\e6ab"`,
	"chrome":               `"\e6ac"`,
	"github":               `"\e6ad"`,
	"file-unknown":         `"\e6af"`,
	"file-excel":           `"\e6b0"`,
	"file-ppt":             `"\e6b1"`,
	"file-word":            `"\e6b2"`,
	"file-pdf":             `"\e6b3"`,
	"desktop":              `"\e6b4"`,
	"upload":               `"\e6b6"`,
	"download":             `"\e6b7"`,
	"pie-chart":            `"\e6b8"`,
	"unlock":               `"\e6ba"`,
	"calendar":             `"\e6bb"`,
	"windows-o":            `"\e6bc"`,
	"dot-chart":            `"\e6bd"`,
	"bar-chart":            `"\e6be"`,
	"code":                 `"\e6bf"`,
	"api":                  `"\e951"`,
	"plus-square":          `"\e6c0"`,
	"minus-square":         `"\e6c1"`,
	"close-square":         `"\e6c2"`,
	"close-square-o":       `"\e6c3"`,
	"check-square":         `"\e6c4"`,
	"check-square-o":       `"\e6c5"`,
	"fast-backward":        `"\e6c6"`,
	"fast-forward":         `"\e6c7"`,
	"up-square":            `"\e6c8"`,
	"down-square":          `"\e6c9"`,
	"left-square":          `"\e6ca"`,
	"right-square":         `"\e6cb"`,
	"right-square-o":       `"\e6cc"`,
	"left-square-o":        `"\e6cd"`,
	"down-square-o":        `"\e6ce"`,
	"up-square-o":          `"\e6cf"`,
	"loading":              `"\e64d"`,
	"loading-3-quarters":   `"\e6ae"`,
	"bulb":                 `"\e649"`,
	"select":               `"\e64a"`,
	"addfile":              `"\e910"`,
	"file-add":             `"\e910"`,
	"addfolder":            `"\e914"`,
	"folder-add":           `"\e914"`,
	"switcher":             `"\e913"`,
	"rocket":               `"\e90f"`,
	"dingding":             `"\e923"`,
	"dingding-o":           `"\e925"`,
	"bell":                 `"\e64e"`,
	"disconnect":           `"\e64f"`,
	"database":             `"\e650"`,
	"compass":              `"\e6db"`,
	"barcode":              `"\e652"`,
	"hourglass":            `"\e653"`,
	"key":                  `"\e654"`,
	"flag":                 `"\e655"`,
	"layout":               `"\e656"`,
	"login":                `"\e657"`,
	"printer":              `"\e673"`,
	"sound":                `"\e6e9"`,
	"usb":                  `"\e6d7"`,
	"skin":                 `"\e6d8"`,
	"tool":                 `"\e6d9"`,
	"sync":                 `"\e6da"`,
	"wifi":                 `"\e6d6"`,
	"car":                  `"\e6dc"`,
	"copyright":            `"\e6de"`,
	"schedule":             `"\e6df"`,
	"user-add":             `"\e6ed"`,
	"user-delete":          `"\e6e0"`,
	"usergroup-add":        `"\e6dd"`,
	"usergroup-delete":     `"\e6e1"`,
	"man":                  `"\e6e2"`,
	"woman":                `"\e6ec"`,
	"shop":                 `"\e6e3"`,
	"gift":                 `"\e6e4"`,
	"idcard":               `"\e6e5"`,
	"medicine-box":         `"\e6e6"`,
	"red-envelope":         `"\e6e7"`,
	"coffee":               `"\e6e8"`,
	"trademark":            `"\e651"`,
	"safety":               `"\e6ea"`,
	"wallet":               `"\e6eb"`,
	"bank":                 `"\e6ee"`,
	"trophy":               `"\e6ef"`,
	"contacts":             `"\e6f0"`,
	"global":               `"\e6f1"`,
	"shake":                `"\e94f"`,
	"fork":                 `"\e6f2"`,
	"dashboard":            `"\e99a"`,
	"profile":              `"\e999"`,
	"table":                `"\e998"`,
	"warning":              `"\e997"`,
	"form":                 `"\e996"`,
	"weibo-square":         `"\e6f5"`,
	"weibo-circle":         `"\e6f4"`,
	"taobao-circle":        `"\e6f3"`,
	"html5":                `"\e9c7"`,
	"weibo":                `"\e9c6"`,
	"twitter":              `"\e9c5"`,
	"wechat":               `"\e9c4"`,
	"youtube":              `"\e9c3"`,
	"alipay-circle":        `"\e9c2"`,
	"taobao":               `"\e9c1"`,
	"skype":                `"\e9c0"`,
	"qq":                   `"\e9bf"`,
	"medium-workmark":      `"\e9be"`,
	"gitlab":               `"\e9bd"`,
	"medium":               `"\e9bc"`,
	"linkedin":             `"\e9bb"`,
	"google-plus":          `"\e9ba"`,
	"dropbox":              `"\e9b9"`,
	"facebook":             `"\e9b8"`,
	"codepen":              `"\e9b7"`,
	"amazon":               `"\e9b6"`,
	"google":               `"\e9b5"`,
	"codepen-circle":       `"\e9b4"`,
	"alipay":               `"\e9b3"`,
	"ant-design":           `"\e9b2"`,
	"aliyun":               `"\e9f4"`,
	"zhihu":                `"\e703"`,
	"file-markdown":        `"\e704"`,
	"slack":                `"\e705"`,
	"slack-square":         `"\e706"`,
	"behance":              `"\e707"`,
	"behance-square":       `"\e708"`,
	"dribbble":             `"\e709"`,
	"dribbble-square":      `"\e70a"`,
	"instagram":            `"\e70b"`,
	"yuque":                `"\e70c"`,
}
