// Code generated by gnorm, DO NOT EDIT!

package db

import (
	"database/sql"
	"time"

	"github.com/lib/pq"
	"github.com/lib/pq/hstore"
	uuid "github.com/satori/go.uuid"
)

// JsonbField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type JsonbField string

// Equals returns a WhereClause for this field.
func (f JsonbField) Equals(v Jsonb) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f JsonbField) GreaterThan(v Jsonb) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f JsonbField) LessThan(v Jsonb) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f JsonbField) GreaterOrEqual(v Jsonb) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f JsonbField) LessOrEqual(v Jsonb) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f JsonbField) NotEqual(v Jsonb) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f JsonbField) In(vals []Jsonb) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// IntField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type IntField string

// Equals returns a WhereClause for this field.
func (f IntField) Equals(v int) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f IntField) GreaterThan(v int) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f IntField) LessThan(v int) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f IntField) GreaterOrEqual(v int) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f IntField) LessOrEqual(v int) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f IntField) NotEqual(v int) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f IntField) In(vals []int) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// StringField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type StringField string

// Equals returns a WhereClause for this field.
func (f StringField) Equals(v string) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f StringField) GreaterThan(v string) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f StringField) LessThan(v string) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f StringField) GreaterOrEqual(v string) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f StringField) LessOrEqual(v string) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f StringField) NotEqual(v string) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f StringField) In(vals []string) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// SqlNullStringField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type SqlNullStringField string

// Equals returns a WhereClause for this field.
func (f SqlNullStringField) Equals(v sql.NullString) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f SqlNullStringField) GreaterThan(v sql.NullString) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f SqlNullStringField) LessThan(v sql.NullString) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f SqlNullStringField) GreaterOrEqual(v sql.NullString) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f SqlNullStringField) LessOrEqual(v sql.NullString) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f SqlNullStringField) NotEqual(v sql.NullString) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f SqlNullStringField) In(vals []sql.NullString) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// Int64Field is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type Int64Field string

// Equals returns a WhereClause for this field.
func (f Int64Field) Equals(v int64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f Int64Field) GreaterThan(v int64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f Int64Field) LessThan(v int64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f Int64Field) GreaterOrEqual(v int64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f Int64Field) LessOrEqual(v int64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f Int64Field) NotEqual(v int64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f Int64Field) In(vals []int64) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// SqlNullInt64Field is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type SqlNullInt64Field string

// Equals returns a WhereClause for this field.
func (f SqlNullInt64Field) Equals(v sql.NullInt64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f SqlNullInt64Field) GreaterThan(v sql.NullInt64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f SqlNullInt64Field) LessThan(v sql.NullInt64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f SqlNullInt64Field) GreaterOrEqual(v sql.NullInt64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f SqlNullInt64Field) LessOrEqual(v sql.NullInt64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f SqlNullInt64Field) NotEqual(v sql.NullInt64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f SqlNullInt64Field) In(vals []sql.NullInt64) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// Float64Field is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type Float64Field string

// Equals returns a WhereClause for this field.
func (f Float64Field) Equals(v float64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f Float64Field) GreaterThan(v float64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f Float64Field) LessThan(v float64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f Float64Field) GreaterOrEqual(v float64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f Float64Field) LessOrEqual(v float64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f Float64Field) NotEqual(v float64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f Float64Field) In(vals []float64) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// SqlNullFloat64Field is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type SqlNullFloat64Field string

// Equals returns a WhereClause for this field.
func (f SqlNullFloat64Field) Equals(v sql.NullFloat64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f SqlNullFloat64Field) GreaterThan(v sql.NullFloat64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f SqlNullFloat64Field) LessThan(v sql.NullFloat64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f SqlNullFloat64Field) GreaterOrEqual(v sql.NullFloat64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f SqlNullFloat64Field) LessOrEqual(v sql.NullFloat64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f SqlNullFloat64Field) NotEqual(v sql.NullFloat64) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f SqlNullFloat64Field) In(vals []sql.NullFloat64) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// BoolField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type BoolField string

// Equals returns a WhereClause for this field.
func (f BoolField) Equals(v bool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f BoolField) GreaterThan(v bool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f BoolField) LessThan(v bool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f BoolField) GreaterOrEqual(v bool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f BoolField) LessOrEqual(v bool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f BoolField) NotEqual(v bool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f BoolField) In(vals []bool) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// SqlNullBoolField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type SqlNullBoolField string

// Equals returns a WhereClause for this field.
func (f SqlNullBoolField) Equals(v sql.NullBool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f SqlNullBoolField) GreaterThan(v sql.NullBool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f SqlNullBoolField) LessThan(v sql.NullBool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f SqlNullBoolField) GreaterOrEqual(v sql.NullBool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f SqlNullBoolField) LessOrEqual(v sql.NullBool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f SqlNullBoolField) NotEqual(v sql.NullBool) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f SqlNullBoolField) In(vals []sql.NullBool) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// TimeTimeField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type TimeTimeField string

// Equals returns a WhereClause for this field.
func (f TimeTimeField) Equals(v time.Time) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f TimeTimeField) GreaterThan(v time.Time) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f TimeTimeField) LessThan(v time.Time) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f TimeTimeField) GreaterOrEqual(v time.Time) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f TimeTimeField) LessOrEqual(v time.Time) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f TimeTimeField) NotEqual(v time.Time) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f TimeTimeField) In(vals []time.Time) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// PqNullTimeField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type PqNullTimeField string

// Equals returns a WhereClause for this field.
func (f PqNullTimeField) Equals(v pq.NullTime) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f PqNullTimeField) GreaterThan(v pq.NullTime) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f PqNullTimeField) LessThan(v pq.NullTime) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f PqNullTimeField) GreaterOrEqual(v pq.NullTime) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f PqNullTimeField) LessOrEqual(v pq.NullTime) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f PqNullTimeField) NotEqual(v pq.NullTime) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f PqNullTimeField) In(vals []pq.NullTime) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// Uint32Field is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type Uint32Field string

// Equals returns a WhereClause for this field.
func (f Uint32Field) Equals(v uint32) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f Uint32Field) GreaterThan(v uint32) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f Uint32Field) LessThan(v uint32) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f Uint32Field) GreaterOrEqual(v uint32) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f Uint32Field) LessOrEqual(v uint32) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f Uint32Field) NotEqual(v uint32) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f Uint32Field) In(vals []uint32) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// UuidUUIDField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type UuidUUIDField string

// Equals returns a WhereClause for this field.
func (f UuidUUIDField) Equals(v uuid.UUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f UuidUUIDField) GreaterThan(v uuid.UUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f UuidUUIDField) LessThan(v uuid.UUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f UuidUUIDField) GreaterOrEqual(v uuid.UUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f UuidUUIDField) LessOrEqual(v uuid.UUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f UuidUUIDField) NotEqual(v uuid.UUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f UuidUUIDField) In(vals []uuid.UUID) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// UuidNullUUIDField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type UuidNullUUIDField string

// Equals returns a WhereClause for this field.
func (f UuidNullUUIDField) Equals(v uuid.NullUUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f UuidNullUUIDField) GreaterThan(v uuid.NullUUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f UuidNullUUIDField) LessThan(v uuid.NullUUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f UuidNullUUIDField) GreaterOrEqual(v uuid.NullUUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f UuidNullUUIDField) LessOrEqual(v uuid.NullUUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f UuidNullUUIDField) NotEqual(v uuid.NullUUID) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f UuidNullUUIDField) In(vals []uuid.NullUUID) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// HstoreHstoreField is a component that returns a WhereClause that contains a
// comparison based on its field and a strongly typed value.
type HstoreHstoreField string

// Equals returns a WhereClause for this field.
func (f HstoreHstoreField) Equals(v hstore.Hstore) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompEqual,
		Value: v,
	}
}

// GreaterThan returns a WhereClause for this field.
func (f HstoreHstoreField) GreaterThan(v hstore.Hstore) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGreater,
		Value: v,
	}
}

// LessThan returns a WhereClause for this field.
func (f HstoreHstoreField) LessThan(v hstore.Hstore) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLess,
		Value: v,
	}
}

// GreaterOrEqual returns a WhereClause for this field.
func (f HstoreHstoreField) GreaterOrEqual(v hstore.Hstore) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompGTE,
		Value: v,
	}
}

// LessOrEqual returns a WhereClause for this field.
func (f HstoreHstoreField) LessOrEqual(v hstore.Hstore) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompLTE,
		Value: v,
	}
}

// NotEqual returns a WhereClause for this field.
func (f HstoreHstoreField) NotEqual(v hstore.Hstore) WhereClause {
	return Where{
		Field: string(f),
		Comp:  CompNE,
		Value: v,
	}
}

// In returns a WhereClause for this field.
func (f HstoreHstoreField) In(vals []hstore.Hstore) WhereClause {
	values := make([]interface{}, len(vals))
	for x := range vals {
		values[x] = vals[x]
	}
	return InClause{
		Field: string(f),
		Vals:  values,
	}
}

// IsNull returns a WhereClause that matches when this field is NULL.
func (f JsonbField) IsNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  true,
	}
}

// IsNotNull returns a WhereClause that matches when this field is not NULL.
func (f JsonbField) IsNotNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  false,
	}
}

// IsNull returns a WhereClause that matches when this field is NULL.
func (f SqlNullStringField) IsNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  true,
	}
}

// IsNotNull returns a WhereClause that matches when this field is not NULL.
func (f SqlNullStringField) IsNotNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  false,
	}
}

// IsNull returns a WhereClause that matches when this field is NULL.
func (f SqlNullInt64Field) IsNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  true,
	}
}

// IsNotNull returns a WhereClause that matches when this field is not NULL.
func (f SqlNullInt64Field) IsNotNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  false,
	}
}

// IsNull returns a WhereClause that matches when this field is NULL.
func (f SqlNullFloat64Field) IsNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  true,
	}
}

// IsNotNull returns a WhereClause that matches when this field is not NULL.
func (f SqlNullFloat64Field) IsNotNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  false,
	}
}

// IsNull returns a WhereClause that matches when this field is NULL.
func (f SqlNullBoolField) IsNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  true,
	}
}

// IsNotNull returns a WhereClause that matches when this field is not NULL.
func (f SqlNullBoolField) IsNotNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  false,
	}
}

// IsNull returns a WhereClause that matches when this field is NULL.
func (f PqNullTimeField) IsNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  true,
	}
}

// IsNotNull returns a WhereClause that matches when this field is not NULL.
func (f PqNullTimeField) IsNotNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  false,
	}
}

// IsNull returns a WhereClause that matches when this field is NULL.
func (f UuidNullUUIDField) IsNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  true,
	}
}

// IsNotNull returns a WhereClause that matches when this field is not NULL.
func (f UuidNullUUIDField) IsNotNull() WhereClause {
	return NullClause{
		Field: string(f),
		Null:  false,
	}
}
