package zoom

import (
	"github.com/gernest/gs"
	"github.com/gernest/vected/web/mixins"
	"github.com/gernest/vected/web/style/core/themes"
)

func Motion(klass, keyframe, duration string) gs.CSSRule {
	return gs.CSS(
		mixins.MakeMotion(klass, keyframe, duration),
		gs.S(klass+"-enter",
			gs.S("&,"+klass+"-appear",
				gs.P("transform", "scale(0)"),
				gs.P("animation-timing-function", themes.Default.EaseOutCirc),
			),
		),
		gs.S(klass+"-leave",
			gs.P("animation-timing-function", themes.Default.EaseInOutCirc),
		),
	)
}

const (
	Zoom  = "zoom"
	Big   = "zoomBig"
	Up    = "zoomUp"
	Left  = "zoomLeft"
	Right = "zoomRight"
	Down  = "zoomDown"
)

func KeyFrames() gs.CSSRule {
	return gs.CSS(
		gs.KeyFrame(Zoom+"In",
			gs.S("0%",
				gs.P("opacity", "0"),
				gs.P("transform", "scale(0.2)"),
			),
			gs.S("100%",
				gs.P("opacity", "1"),
				gs.P("transform", "scale(1)"),
			),
		),
		gs.KeyFrame(Zoom+"Out",
			gs.S("0%",
				gs.P("transform", "scale(1)"),
			),
			gs.S("100%",
				gs.P("opacity", "0"),
				gs.P("transform", "scale(0.2)"),
			),
		),
		gs.KeyFrame(Big+"In",
			gs.S("0%",
				gs.P("opacity", "0"),
				gs.P("transform", "scale(.8)"),
			),
			gs.S("100%",
				gs.P("transform", "scale(1)"),
			),
		),
		gs.KeyFrame(Big+"Out",
			gs.S("0%",
				gs.P("transform", "scale(1)"),
			),
			gs.S("100%",
				gs.P("opacity", "0"),
				gs.P("transform", "scale(.8)"),
			),
		),
		gs.KeyFrame(Up+"In",
			gs.S("0%",
				gs.P("opacity", "0"),
				gs.P("transform-origin", "50% 0%"),
				gs.P("transform", "scale(.8)"),
			),
			gs.S("100%",
				gs.P("transform-origin", "50% 0%"),
				gs.P("transform", "scale(1)"),
			),
		),
		gs.KeyFrame(Up+"Out",
			gs.S("0%",
				gs.P("transform-origin", "50% 0%"),
				gs.P("transform", "scale(1)"),
			),
			gs.S("100%",
				gs.P("opacity", "0"),
				gs.P("transform-origin", "50% 0%"),
				gs.P("transform", "scale(.8)"),
			),
		),
		gs.KeyFrame(Left+"In",
			gs.S("0%",
				gs.P("opacity", "0"),
				gs.P("transform-origin", "0% 50%"),
				gs.P("transform", "scale(.8)"),
			),
			gs.S("100%",
				gs.P("transform-origin", "0% 50%"),
				gs.P("transform", "scale(1)"),
			),
		),
		gs.KeyFrame(Left+"Out",
			gs.S("0%",
				gs.P("transform-origin", "0% 50%"),
				gs.P("transform", "scale(1)"),
			),
			gs.S("100%",
				gs.P("opacity", "0"),
				gs.P("transform-origin", "0% 50%"),
				gs.P("transform", "scale(.8)"),
			),
		),
		gs.KeyFrame(Right+"In",
			gs.S("0%",
				gs.P("opacity", "0"),
				gs.P("transform-origin", "100% 50%"),
				gs.P("transform", "scale(.8)"),
			),
			gs.S("100%",
				gs.P("transform-origin", "100% 50%"),
				gs.P("transform", "scale(1)"),
			),
		),
		gs.KeyFrame(Right+"Out",
			gs.S("0%",
				gs.P("transform-origin", "100% 50%"),
				gs.P("transform", "scale(1)"),
			),
			gs.S("100%",
				gs.P("opacity", "0"),
				gs.P("transform-origin", "100% 50%"),
				gs.P("transform", "scale(.8)"),
			),
		),
		gs.KeyFrame(Down+"In",
			gs.S("0%",
				gs.P("opacity", "0"),
				gs.P("transform-origin", "50% 100%"),
				gs.P("transform", "scale(.8)"),
			),
			gs.S("100%",
				gs.P("transform-origin", "50% 100%"),
				gs.P("transform", "scale(1)"),
			),
		),
		gs.KeyFrame(Down+"Out",
			gs.S("0%",
				gs.P("transform-origin", "50% 100%"),
				gs.P("transform", "scale(1)"),
			),
			gs.S("100%",
				gs.P("opacity", "0"),
				gs.P("transform-origin", "50% 100%"),
				gs.P("transform", "scale(.8)"),
			),
		),
	)
}
