// Code generated by vected DO NOT EDIT.
package sample

import (
	"github.com/gernest/vected/lib/xhtml"
	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

// Render implements vected.Renderer interface.
func (Component) Render() *xhtml.Node {
	return &xhtml.Node{Children: []*xhtml.Node{&xhtml.Node{Type: html.ElementNode, DataAtom: atom.Html, Data: "html", Attr: []html.Attribute{}, Children: []*xhtml.Node{&xhtml.Node{Type: html.ElementNode, DataAtom: atom.Head, Data: "head", Attr: []html.Attribute{}}, &xhtml.Node{Type: html.ElementNode, DataAtom: atom.Body, Data: "body", Attr: []html.Attribute{}, Children: []*xhtml.Node{&xhtml.Node{Type: html.ElementNode, DataAtom: atom.Div, Data: "div", Attr: []html.Attribute{}, Children: []*xhtml.Node{&xhtml.Node{Type: html.TextNode, Data: " hello, world", Attr: []html.Attribute{}}}}}}}}}}
}
