package core

import (
	"github.com/gernest/gs"
	"github.com/gernest/vected/style/mixins"
	"github.com/gernest/vected/style/themes"
)

func FontFace() gs.CSSRule {
	u := src(".woff") + `format('woff'),` +
		src(".ttf") + `format('truetype'),` +
		src(".svg#iconfont'") + `format('svg')`
	return gs.FontFace(
		gs.P("font-family", "'anticon'"),
		gs.P("src", src(".eot")),
		gs.P("src", u),
	)
}

func src(ext string) string {
	return "url('" + themes.Default.IconURL + "')" + ext
}

func NewFontFace() gs.CSSRule {
	return gs.CSS(
		gs.S("."+themes.Default.IconFontPrefix, mixins.IconFont()),
	)
}

func styleIcon(name, content string) gs.CSSRule {
	return gs.S(themes.Default.IconFontPrefix+"-"+name,
		gs.P("content", content),
	)
}

func AllIcons() gs.CSSRule {
	var list gs.RuleList
	for k, v := range icons {
		list = append(list, styleIcon(k, v))
	}
	list = append(list, gs.S(themes.Default.IconFontPrefix+"-spin:before",
		gs.P("display", "inline-block"),
		gs.P("animation", "loadingCircle 1s infinite linear"),
	))
	return list
}

var icons = map[string]string{
	"step-forward:before":         `"\e600"`,
	"step-backward:before":        `"\e601"`,
	"forward:before":              `"\e602"`,
	"backward:before":             `"\e603"`,
	"caret-right:before":          `"\e604"`,
	"caret-left:before":           `"\e605"`,
	"caret-down:before":           `"\e606"`,
	"caret-up:before":             `"\e607"`,
	"right-circle:before":         `"\e608"`,
	"circle-right:before":         `"\e608"`, // antd@1.x compatibility alias: right-circle
	"caret-circle-right:before":   `"\e608"`, // antd@1.x compatibility alias: right-circle
	"left-circle:before":          `"\e609"`,
	"circle-left:before":          `"\e609"`, // antd@1.x compatibility alias: left-circle
	"caret-circle-left:before":    `"\e609"`, // antd@1.x compatibility alias: left-circle
	"up-circle:before":            `"\e60a"`,
	"circle-up:before":            `"\e60a"`, // antd@1.x compatibility alias: up-circle
	"caret-circle-up:before":      `"\e60a"`, // antd@1.x compatibility alias: up-circle
	"down-circle:before":          `"\e60b"`,
	"circle-down:before":          `"\e60b"`, // antd@1.x compatibility alias: down-circle
	"caret-circle-down:before":    `"\e60b"`, // antd@1.x compatibility alias: down-circle
	"right-circle-o:before":       `"\e60c"`,
	"circle-o-right:before":       `"\e60c"`, // antd@1.x compatibility alias: right-circle-o
	"caret-circle-o-right:before": `"\e60c"`, // antd@1.x compatibility alias: right-circle-o
	"left-circle-o:before":        `"\e60d"`,
	"circle-o-left:before":        `"\e60d"`, // antd@1.x compatibility alias: left-circle-o
	"caret-circle-o-left:before":  `"\e60d"`, // antd@1.x compatibility alias: left-circle-o
	"up-circle-o:before":          `"\e60e"`,
	"circle-o-up:before":          `"\e60e"`, // antd@1.x compatibility alias: up-circle-o
	"caret-circle-o-up:before":    `"\e60e"`, // antd@1.x compatibility alias: up-circle-o
	"down-circle-o:before":        `"\e60f"`,
	"circle-o-down:before":        `"\e60f"`, // antd@1.x compatibility alias: down-circle-o
	"caret-circle-o-down:before":  `"\e60f"`, // antd@1.x compatibility alias: down-circle-o
	"verticle-left:before":        `"\e610"`,
	"verticle-right:before":       `"\e611"`,
	"rollback:before":             `"\e612"`,
	"retweet:before":              `"\e613"`,
	"shrink:before":               `"\e614"`,
	"arrows-alt:before":           `"\e615"`,
	"arrow-salt:before":           `"\e615"`, // antd@1.x compatibility alias: arrows-alt
	"reload:before":               `"\e616"`,
	"double-right:before":         `"\e617"`,
	"double-left:before":          `"\e618"`,
	"arrow-down:before":           `"\e619"`,
	"arrow-up:before":             `"\e61a"`,
	"arrow-right:before":          `"\e61b"`,
	"arrow-left:before":           `"\e61c"`,
	"down:before":                 `"\e61d"`,
	"up:before":                   `"\e61e"`,
	"right:before":                `"\e61f"`,
	"left:before":                 `"\e620"`,
	"minus-square-o:before":       `"\e621"`,
	"minus-circle:before":         `"\e622"`,
	"minus-circle-o:before":       `"\e623"`,
	"minus:before":                `"\e624"`,
	"plus-circle-o:before":        `"\e625"`,
	"plus-circle:before":          `"\e626"`,
	"plus:before":                 `"\e627"`,
	"info-circle:before":          `"\e628"`,
	"info-circle-o:before":        `"\e629"`,
	"info:before":                 `"\e62a"`,
	"exclamation:before":          `"\e62b"`,
	"exclamation-circle:before":   `"\e62c"`,
	"exclamation-circle-o:before": `"\e62d"`,
	"close-circle:before":         `"\e62e"`,
	"cross-circle:before":         `"\e62e"`, // antd@1.x compatibility alias: close-circle
	"close-circle-o:before":       `"\e62f"`,
	"cross-circle-o:before":       `"\e62f"`, // antd@1.x compatibility alias: close-circle-o
	"check-circle:before":         `"\e630"`,
	"check-circle-o:before":       `"\e631"`,
	"check:before":                `"\e632"`,
	"close:before":                `"\e633"`,
	"cross:before":                `"\e633"`, // antd@1.x compatibility alias: close
	"customer-service:before":     `"\e634"`,
	"customerservice:before":      `"\e634"`, // antd@1.x compatibility alias: customer-service
	"credit-card:before":          `"\e635"`,
	"code-o:before":               `"\e636"`,
	"book:before":                 `"\e637"`,
	"bars:before":                 `"\e639"`,
	"question:before":             `"\e63a"`,
	"question-circle:before":      `"\e63b"`,
	"question-circle-o:before":    `"\e63c"`,
	"pause:before":                `"\e63d"`,
	"pause-circle:before":         `"\e63e"`,
	"pause-circle-o:before":       `"\e63f"`,
	"clock-circle:before":         `"\e640"`,
	"clock-circle-o:before":       `"\e641"`,
	"swap:before":                 `"\e642"`,
	"swap-left:before":            `"\e643"`,
	"swap-right:before":           `"\e644"`,
	"plus-square-o:before":        `"\e645"`,
	"frown:before":                `"\e646"`,
	"frown-circle:before":         `"\e646"`, // antd@1.x compatibility alias: frown
	"ellipsis:before":             `"\e647"`,
	"copy:before":                 `"\e648"`,
	"menu-fold:before":            `"\e9ac"`,
	"mail:before":                 `"\e659"`,
	"logout:before":               `"\e65a"`,
	"link:before":                 `"\e65b"`,
	"area-chart:before":           `"\e65c"`,
	"line-chart:before":           `"\e65d"`,
	"home:before":                 `"\e65e"`,
	"laptop:before":               `"\e65f"`,
	"star:before":                 `"\e660"`,
	"star-o:before":               `"\e661"`,
	"folder:before":               `"\e662"`,
	"filter:before":               `"\e663"`,
	"file:before":                 `"\e664"`,
	"exception:before":            `"\e665"`,
	"meh:before":                  `"\e666"`,
	"meh-circle:before":           `"\e666"`, // antd@1.x compatibility alias: meh
	"meh-o:before":                `"\e667"`,
	"shopping-cart:before":        `"\e668"`,
	"save:before":                 `"\e669"`,
	"user:before":                 `"\e66a"`,
	"video-camera:before":         `"\e66b"`,
	"to-top:before":               `"\e66c"`,
	"team:before":                 `"\e66d"`,
	"tablet:before":               `"\e66e"`,
	"solution:before":             `"\e66f"`,
	"search:before":               `"\e670"`,
	"share-alt:before":            `"\e671"`,
	"setting:before":              `"\e672"`,
	"poweroff:before":             `"\e6d5"`,
	"picture:before":              `"\e674"`,
	"phone:before":                `"\e675"`,
	"paper-clip:before":           `"\e676"`,
	"notification:before":         `"\e677"`,
	"mobile:before":               `"\e678"`,
	"menu-unfold:before":          `"\e9ad"`,
	"inbox:before":                `"\e67a"`,
	"lock:before":                 `"\e67b"`,
	"qrcode:before":               `"\e67c"`,
	"play-circle:before":          `"\e6d0"`,
	"play-circle-o:before":        `"\e6d1"`,
	"tag:before":                  `"\e6d2"`,
	"tag-o:before":                `"\e6d3"`,
	"tags:before":                 `"\e67d"`,
	"tags-o:before":               `"\e67e"`,
	"cloud-o:before":              `"\e67f"`,
	"cloud:before":                `"\e680"`,
	"cloud-upload:before":         `"\e681"`,
	"cloud-download:before":       `"\e682"`,
	"cloud-download-o:before":     `"\e683"`,
	"cloud-upload-o:before":       `"\e684"`,
	"environment:before":          `"\e685"`,
	"environment-o:before":        `"\e686"`,
	"eye:before":                  `"\e687"`,
	"eye-o:before":                `"\e688"`,
	"camera:before":               `"\e689"`,
	"camera-o:before":             `"\e68a"`,
	"windows:before":              `"\e68b"`,
	"apple:before":                `"\e68c"`,
	"apple-o:before":              `"\e6d4"`,
	"android:before":              `"\e938"`,
	"android-o:before":            `"\e68d"`,
	"aliwangwang:before":          `"\e68e"`,
	"aliwangwang-o:before":        `"\e68f"`,
	"export:before":               `"\e691"`,
	"edit:before":                 `"\e692"`,
	"circle-down-o:before":        `"\e693"`,
	"circle-down-:before":         `"\e694"`,
	"appstore-o:before":           `"\e695"`,
	"appstore:before":             `"\e696"`,
	"scan:before":                 `"\e697"`,
	"file-text:before":            `"\e698"`,
	"folder-open:before":          `"\e699"`,
	"hdd:before":                  `"\e69a"`,
	"ie:before":                   `"\e69b"`,
	"file-jpg:before":             `"\e69c"`,
	"like:before":                 `"\e64c"`,
	"like-o:before":               `"\e69d"`,
	"dislike:before":              `"\e64b"`,
	"dislike-o:before":            `"\e69e"`,
	"delete:before":               `"\e69f"`,
	"enter:before":                `"\e6a0"`,
	"pushpin-o:before":            `"\e6a1"`,
	"pushpin:before":              `"\e6a2"`,
	"heart:before":                `"\e6a3"`,
	"heart-o:before":              `"\e6a4"`,
	"pay-circle:before":           `"\e6a5"`,
	"pay-circle-o:before":         `"\e6a6"`,
	"smile:before":                `"\e6a7"`,
	"smile-circle:before":         `"\e6a7"`, // antd@1.x compatibility alias: smile
	"smile-o:before":              `"\e6a8"`,
	"frown-o:before":              `"\e6a9"`,
	"calculator:before":           `"\e6aa"`,
	"message:before":              `"\e6ab"`,
	"chrome:before":               `"\e6ac"`,
	"github:before":               `"\e6ad"`,
	"file-unknown:before":         `"\e6af"`,
	"file-excel:before":           `"\e6b0"`,
	"file-ppt:before":             `"\e6b1"`,
	"file-word:before":            `"\e6b2"`,
	"file-pdf:before":             `"\e6b3"`,
	"desktop:before":              `"\e6b4"`,
	"upload:before":               `"\e6b6"`,
	"download:before":             `"\e6b7"`,
	"pie-chart:before":            `"\e6b8"`,
	"unlock:before":               `"\e6ba"`,
	"calendar:before":             `"\e6bb"`,
	"windows-o:before":            `"\e6bc"`,
	"dot-chart:before":            `"\e6bd"`,
	"bar-chart:before":            `"\e6be"`,
	"code:before":                 `"\e6bf"`,
	"api:before":                  `"\e951"`,
	"plus-square:before":          `"\e6c0"`,
	"minus-square:before":         `"\e6c1"`,
	"close-square:before":         `"\e6c2"`,
	"close-square-o:before":       `"\e6c3"`,
	"check-square:before":         `"\e6c4"`,
	"check-square-o:before":       `"\e6c5"`,
	"fast-backward:before":        `"\e6c6"`,
	"fast-forward:before":         `"\e6c7"`,
	"up-square:before":            `"\e6c8"`,
	"down-square:before":          `"\e6c9"`,
	"left-square:before":          `"\e6ca"`,
	"right-square:before":         `"\e6cb"`,
	"right-square-o:before":       `"\e6cc"`,
	"left-square-o:before":        `"\e6cd"`,
	"down-square-o:before":        `"\e6ce"`,
	"up-square-o:before":          `"\e6cf"`,
	"loading:before":              `"\e64d"`,
	"loading-3-quarters:before":   `"\e6ae"`,
	"bulb:before":                 `"\e649"`,
	"select:before":               `"\e64a"`,
	"addfile:before":              `"\e910"`,
	"file-add:before":             `"\e910"`,
	"addfolder:before":            `"\e914"`,
	"folder-add:before":           `"\e914"`,
	"switcher:before":             `"\e913"`,
	"rocket:before":               `"\e90f"`,
	"dingding:before":             `"\e923"`,
	"dingding-o:before":           `"\e925"`,
	"bell:before":                 `"\e64e"`,
	"disconnect:before":           `"\e64f"`,
	"database:before":             `"\e650"`,
	"compass:before":              `"\e6db"`,
	"barcode:before":              `"\e652"`,
	"hourglass:before":            `"\e653"`,
	"key:before":                  `"\e654"`,
	"flag:before":                 `"\e655"`,
	"layout:before":               `"\e656"`,
	"login:before":                `"\e657"`,
	"printer:before":              `"\e673"`,
	"sound:before":                `"\e6e9"`,
	"usb:before":                  `"\e6d7"`,
	"skin:before":                 `"\e6d8"`,
	"tool:before":                 `"\e6d9"`,
	"sync:before":                 `"\e6da"`,
	"wifi:before":                 `"\e6d6"`,
	"car:before":                  `"\e6dc"`,
	"copyright:before":            `"\e6de"`,
	"schedule:before":             `"\e6df"`,
	"user-add:before":             `"\e6ed"`,
	"user-delete:before":          `"\e6e0"`,
	"usergroup-add:before":        `"\e6dd"`,
	"usergroup-delete:before":     `"\e6e1"`,
	"man:before":                  `"\e6e2"`,
	"woman:before":                `"\e6ec"`,
	"shop:before":                 `"\e6e3"`,
	"gift:before":                 `"\e6e4"`,
	"idcard:before":               `"\e6e5"`,
	"medicine-box:before":         `"\e6e6"`,
	"red-envelope:before":         `"\e6e7"`,
	"coffee:before":               `"\e6e8"`,
	"trademark:before":            `"\e651"`,
	"safety:before":               `"\e6ea"`,
	"wallet:before":               `"\e6eb"`,
	"bank:before":                 `"\e6ee"`,
	"trophy:before":               `"\e6ef"`,
	"contacts:before":             `"\e6f0"`,
	"global:before":               `"\e6f1"`,
	"shake:before":                `"\e94f"`,
	"fork:before":                 `"\e6f2"`,
	"dashboard:before":            `"\e99a"`,
	"profile:before":              `"\e999"`,
	"table:before":                `"\e998"`,
	"warning:before":              `"\e997"`,
	"form:before":                 `"\e996"`,
	"weibo-square:before":         `"\e6f5"`,
	"weibo-circle:before":         `"\e6f4"`,
	"taobao-circle:before":        `"\e6f3"`,
	"html5:before":                `"\e9c7"`,
	"weibo:before":                `"\e9c6"`,
	"twitter:before":              `"\e9c5"`,
	"wechat:before":               `"\e9c4"`,
	"youtube:before":              `"\e9c3"`,
	"alipay-circle:before":        `"\e9c2"`,
	"taobao:before":               `"\e9c1"`,
	"skype:before":                `"\e9c0"`,
	"qq:before":                   `"\e9bf"`,
	"medium-workmark:before":      `"\e9be"`,
	"gitlab:before":               `"\e9bd"`,
	"medium:before":               `"\e9bc"`,
	"linkedin:before":             `"\e9bb"`,
	"google-plus:before":          `"\e9ba"`,
	"dropbox:before":              `"\e9b9"`,
	"facebook:before":             `"\e9b8"`,
	"codepen:before":              `"\e9b7"`,
	"amazon:before":               `"\e9b6"`,
	"google:before":               `"\e9b5"`,
	"codepen-circle:before":       `"\e9b4"`,
	"alipay:before":               `"\e9b3"`,
	"ant-design:before":           `"\e9b2"`,
	"aliyun:before":               `"\e9f4"`,
	"zhihu:before":                `"\e703"`,
	"file-markdown:before":        `"\e704"`,
	"slack:before":                `"\e705"`,
	"slack-square:before":         `"\e706"`,
	"behance:before":              `"\e707"`,
	"behance-square:before":       `"\e708"`,
	"dribbble:before":             `"\e709"`,
	"dribbble-square:before":      `"\e70a"`,
	"instagram:before":            `"\e70b"`,
	"yuque:before":                `"\e70c"`,
}
