// Code generated by vected DO NOT EDIT.
package cmp

import (
	"context"
	"fmt"

	"github.com/gernest/vected"
)

var H = vected.NewNode
var HA = vected.Attr
var HAT = vected.Attrs

// Render implements vected.Renderer interface.
func (s SimpleComponent) Render(ctx context.Context, props vected.Props, state vected.State) *vected.Node {
	return H(3, "", "__internal_container___", nil,
		H(3, "", "div", nil,
			H(3, "", "span", nil,
				H(1, "", fmt.Sprintf("%v%v%s%v%s", "\n\t\t\t", props.String("initialName"), "/", s.State().String("name"), "\n\t\t"), nil))))
}
